{{- if .Values.jenkins.openId.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-jenkins-openid"
type: Opaque
data:
  clientId: {{ .Values.jenkins.openId.clientId | b64enc }}
  clientSecret: {{ .Values.jenkins.openId.clientSecret | b64enc }}
  tokenServerUrl: {{ .Values.jenkins.openId.tokenServerUrl | b64enc }}
  authServerUrl: {{ .Values.jenkins.openId.authServerUrl | b64enc }}
{{- end }}
